// <auto-generated />
using System;
using BookChain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookChain.Migrations
{
    [DbContext(typeof(BookChainContext))]
    [Migration("20200912133848_users")]
    partial class users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookChain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeRangeMax");

                    b.Property<int>("AgeRangeMin");

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("Genre");

                    b.Property<int>("Price");

                    b.Property<int>("Quantity");

                    b.Property<float>("Rating");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRangeMax = 28,
                            AgeRangeMin = 14,
                            Author = "Naoki Yoshida",
                            Genre = "Fantasy",
                            Price = 20,
                            Quantity = 5,
                            Rating = 9f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 509, DateTimeKind.Local).AddTicks(8199),
                            Title = "A Realm Reborn"
                        },
                        new
                        {
                            Id = 2,
                            AgeRangeMax = 28,
                            AgeRangeMin = 16,
                            Author = "Naoki Yoshida",
                            Genre = "Fantasy",
                            Price = 40,
                            Quantity = 3,
                            Rating = 10f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "Heavensward"
                        },
                        new
                        {
                            Id = 3,
                            AgeRangeMax = 22,
                            AgeRangeMin = 14,
                            Author = "Naoki Yoshida",
                            Genre = "Fantasy",
                            Price = 40,
                            Quantity = 11,
                            Rating = 7f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "Stormblood"
                        },
                        new
                        {
                            Id = 4,
                            AgeRangeMax = 32,
                            AgeRangeMin = 19,
                            Author = "Naoki Yoshida",
                            Genre = "Horror",
                            Price = 40,
                            Quantity = 7,
                            Rating = 8f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "Shadowbringers"
                        },
                        new
                        {
                            Id = 5,
                            AgeRangeMax = 55,
                            AgeRangeMin = 16,
                            Author = "F. C. Yee",
                            Genre = "Fantasy",
                            Price = 67,
                            Quantity = 24,
                            Rating = 8f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "The rise of Kyoshi"
                        },
                        new
                        {
                            Id = 6,
                            AgeRangeMax = 99,
                            AgeRangeMin = 6,
                            Author = "J. R. R. Tolkien",
                            Genre = "Fantasy",
                            Price = 30,
                            Quantity = 18,
                            Rating = 8f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 7,
                            AgeRangeMax = 67,
                            AgeRangeMin = 18,
                            Author = "H. P. Lovecraft",
                            Genre = "Fantasy",
                            Price = 23,
                            Quantity = 45,
                            Rating = 8f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "The Call of Cthulhu"
                        },
                        new
                        {
                            Id = 8,
                            AgeRangeMax = 33,
                            AgeRangeMin = 16,
                            Author = "Someone Someonegton",
                            Genre = "Horror",
                            Price = 54,
                            Quantity = 35,
                            Rating = 8f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "Dexter"
                        },
                        new
                        {
                            Id = 9,
                            AgeRangeMax = 67,
                            AgeRangeMin = 18,
                            Author = "Uncle Bob",
                            Genre = "Programming",
                            Price = 80,
                            Quantity = 42,
                            Rating = 8f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 10,
                            AgeRangeMax = 67,
                            AgeRangeMin = 18,
                            Author = "Coder Coddington",
                            Genre = "Programming",
                            Price = 128,
                            Quantity = 37,
                            Rating = 8f,
                            ReleaseDate = new DateTime(2020, 9, 12, 16, 38, 47, 512, DateTimeKind.Local).AddTicks(8204),
                            Title = "Effective Java"
                        });
                });

            modelBuilder.Entity("BookChain.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildingNumber");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OpeningHours")
                        .IsRequired();

                    b.Property<string>("Owner")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("Street")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingNumber = 2,
                            City = "Rishon Lezion",
                            Country = "Israel",
                            Name = "Bookstore Of Managmenet",
                            OpeningHours = "08:00 - 20:00",
                            Owner = "Doctor Shakshuka",
                            Phone = "03-9634390",
                            Street = "HaDayagim"
                        },
                        new
                        {
                            Id = 2,
                            BuildingNumber = 4,
                            City = "Tel Aviv",
                            Country = "Israel",
                            Name = "Bookstore Of Parties",
                            OpeningHours = "09:00 - 18:00",
                            Owner = "Lady Luck",
                            Phone = "052-0522250",
                            Street = "Shaul Hamelech"
                        },
                        new
                        {
                            Id = 3,
                            BuildingNumber = 8,
                            City = "Eilat",
                            Country = "Israel",
                            Name = "Bookstore Of Seas",
                            OpeningHours = "06:00 - 17:00",
                            Owner = "Mister Surfer",
                            Phone = "050-2386234",
                            Street = "Agmonim"
                        },
                        new
                        {
                            Id = 4,
                            BuildingNumber = 1,
                            City = "Tiberias",
                            Country = "Israel",
                            Name = "Bookstore Of Nothing",
                            OpeningHours = "11:00 - 22:00",
                            Owner = "Cool Chiller",
                            Phone = "08-9423665",
                            Street = "HaKishon"
                        },
                        new
                        {
                            Id = 5,
                            BuildingNumber = 26,
                            City = "Haifa",
                            Country = "Israel",
                            Name = "Bookstore Of Spades",
                            OpeningHours = "08:00 - 21:00",
                            Owner = "Mad Scientist",
                            Phone = "04-5371945",
                            Street = "Tchernichovski"
                        });
                });

            modelBuilder.Entity("BookChain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<DateTime>("JoinDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1981, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "MosheShuki@gmail.com",
                            JoinDate = new DateTime(2020, 9, 12, 16, 38, 47, 513, DateTimeKind.Local).AddTicks(8206),
                            Name = "Moshe Shuki Maashush",
                            Phone = "999-9999999"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1999, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Stichland@gmail.com",
                            JoinDate = new DateTime(2020, 9, 12, 16, 38, 47, 513, DateTimeKind.Local).AddTicks(8206),
                            Name = "Stich Hood",
                            Phone = "404-4045404"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1997, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "naaman123@gmail.com",
                            JoinDate = new DateTime(2020, 9, 12, 16, 38, 47, 513, DateTimeKind.Local).AddTicks(8206),
                            Name = "Naaman Tsur",
                            Phone = "054-342342"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1999, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "liroasdasd@gmail.com",
                            JoinDate = new DateTime(2020, 9, 12, 16, 38, 47, 513, DateTimeKind.Local).AddTicks(8206),
                            Name = "Lior Somdit",
                            Phone = "192-123591"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1968, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "southerntemoke@gmail.com",
                            JoinDate = new DateTime(2020, 9, 12, 16, 38, 47, 513, DateTimeKind.Local).AddTicks(8206),
                            Name = "Kelsang forbes",
                            Phone = "152-1637894"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1965, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yokoyarocks@gmail.com",
                            JoinDate = new DateTime(2020, 9, 12, 16, 38, 47, 513, DateTimeKind.Local).AddTicks(8206),
                            Name = "Jianzhu thumb",
                            Phone = "152-9182734"
                        });
                });

            modelBuilder.Entity("BookChain.Models.Purchase.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId");

                    b.Property<int>("BuyerId");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("PaidPrice");

                    b.Property<int>("SellerId");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("BookChain.Models.Worker.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<DateTime>("JoinDate");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<DateTime>("ResignationDate");

                    b.Property<int>("Salary");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BookChain.Models.Worker.WorkerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "cde8f18f-1301-4dab-bbdf-b8147c985af2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "caa257a1-4432-42cd-b9bc-7166ecb318c6",
                            Name = "Worker",
                            NormalizedName = "WORKER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BookChain.Models.Purchase.Purchase", b =>
                {
                    b.HasOne("BookChain.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookChain.Models.Customer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookChain.Models.Worker.Worker", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BookChain.Models.Worker.WorkerRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BookChain.Models.Worker.Worker")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BookChain.Models.Worker.Worker")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BookChain.Models.Worker.WorkerRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookChain.Models.Worker.Worker")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BookChain.Models.Worker.Worker")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
